[package]
name = "p25_filts"
version = "1.0.2"
authors = ["Mick Koch <mick@kochm.co>", "Mark Tomlin <Dygear@gmail.com"]

[dependencies]
static_fir = {version = "1.0.2",  git = "https://github.com/Dygear/static_fir.rs" }
num = "^0.4.0"
